export const GLOSSARY = {
  reach: "The number of unique people who saw your ads at least once in this period.",
  spend: "Total amount spent on ads in this period.",
  cpmr: "Cost Per Thousand Reached — how much you pay to get your ad in front of 1,000 unique people. Unlike CPM (which counts impressions), CPMR counts distinct individuals, so it tells you the real cost of expanding your audience. A rising CPMR means you're paying more per new person reached — your audience pool is shrinking or getting more competitive.",
  cpp: "Cost Per Purchase — spend divided by number of purchases.",
  frequency: "Average number of times each person saw your ads (impressions ÷ reach).",
  netNew: "Reach this period that wasn't part of the cumulative reach up to the previous period — i.e. genuinely new people.",
  netNewPct: "Net new reach as a % of this period's total reach. Higher means more of your audience is new rather than repeat.",
  newPct: "% of this entity's reach that goes to new (prospecting) audiences — people not in any custom or retargeting audience. Higher is better for audience expansion.",
  cumulativeReach: "Total unique people reached from the start date through this period, deduplicated across the whole span.",
  costPer1kNetNew: "Spend divided by net new reach, times 1,000 — cost to reach 1,000 genuinely new people.",
  prospecting: "New Audience — people not in any of your defined custom/engaged/existing audiences.",
  engaged: "Engaged Audience — people who interacted with your brand (site visit, video view, etc.) but haven't purchased.",
  existing: "Existing Customers — people already in your customer list or who have purchased.",
  overlapPct: "% of this entity's reach that's also reached by other campaigns/ads in the account. Lower means more unique audience.",
  uniqueContribution: "People this campaign/ad reaches that no other campaign/ad in the account reaches.",
  incrementalReach: "New reach added by extending the window one more week — dropping incremental reach signals audience/creative fatigue.",
  cohortSpendPct: "% of that week's total spend going to ads created in this specific week (cohort).",
  attributionWindow: "How long after a click/view Meta still credits a conversion to that ad. 1DC = within 1 day of click, 28DC = within 28 days.",
  upliftRatio: "How much bigger your 28-day purchase count is compared to your 1-day purchase count, as a percentage. Example: 1DC = 10 purchases, 28DC = 30 purchases → uplift = 200%, meaning two-thirds of buyers took more than a day to convert after seeing the ad. Low uplift (under ~20%) = fast buyers, 1-day numbers are reliable. High uplift = buyers take days or weeks, so 1-day numbers are heavily understating real performance.",
  sameDayPct: "% of 28-day attributed purchases that converted within 1 day of the ad click. High = clean same-day conversion signal.",
  saturation: "Share of reach that's Engaged + Existing rather than New — a high number suggests you're mostly re-reaching the same people.",
  // [PM ENHANCEMENT] — Definitions for every purchase/cohort/creator metric so no
  // column or card in the app is left unexplained.
  purchases: "Purchases Meta attributes to your ads in this period, tracked via Pixel or Conversions API.",
  newPurchases: "Purchases made by people in the New Audience segment — genuinely new customers, not repeat buyers.",
  newPurchasePct: "New-customer purchases as a share of all purchases. Higher means your ads acquire customers, not just re-convert existing ones.",
  newCpa: "Cost to acquire one new customer — New Audience spend divided by New Audience purchases.",
  adsInCohort: "How many ads were launched in this month.",
  shareOfTotal: "This cohort's share of all ad spend in the selected period.",
  last7Share: "Share of the most recent week's spend still going to this cohort — 0% means these creatives have been fully replaced.",
  activeDays: "Number of days in the period this cohort had any spend.",
  creatorHandle: "Creator name extracted from the ad's naming convention (ifs_{creator}_ife).",
  partnershipAd: "An ad using Meta's branded content tools — detected via the branded-content fields on its creative.",
} as const;
